# RetailXAI global configuration
global:
  logging:
    level: INFO
    file: logs/retailxai.log
    max_bytes: 10485760  # 10MB
    backup_count: 5
  database:
    host: ${DB_HOST}
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    min_connections: 1
    max_connections: 10
    connect_timeout: 5
  api_keys:
    youtube: ${YOUTUBE_API_KEY}
    claude: ${CLAUDE_API_KEY}
    twitter:
      consumer_key: ${TWITTER_CONSUMER_KEY}
      consumer_secret: ${TWITTER_CONSUMER_SECRET}
      access_token: ${TWITTER_ACCESS_TOKEN}
      access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}
    reddit:
      client_id: ${REDDIT_CLIENT_ID}
      client_secret: ${REDDIT_CLIENT_SECRET}
    substack:
      email_address: ${SUBSTACK_EMAIL_ADDRESS}
      email_user: ${EMAIL_USER}
      email_password: ${EMAIL_PASSWORD}
  claude_model: claude-3-5-sonnet-20241022

# Data sources configuration
sources:
  youtube:
    channels: config/companies.yaml
    keywords:
      - earnings call
      - retail trends
      - CPG
      - consumer behavior
    max_results: 5
  rss:
    feeds: config/companies.yaml
    static_feeds:
      - https://www.prnewswire.com/news-releases/food-and-beverages/
      - https://www.businesswire.com/portal/site/home/news/food-beverage/
  trending:
    reddit:
      client_id: ${REDDIT_CLIENT_ID}
      client_secret: ${REDDIT_CLIENT_SECRET}
      user_agent: "RetailXAI/1.0"
    twitter:
      consumer_key: ${TWITTER_CONSUMER_KEY}
      consumer_secret: ${TWITTER_CONSUMER_SECRET}
      access_token: ${TWITTER_ACCESS_TOKEN}
      access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}
    companies: config/companies.yaml

# Data destinations configuration
destinations:
  substack:
    draft_directory: drafts/substack
    email_drafts: true
    email_recipient: ${DRAFT_EMAIL_RECIPIENT}
  twitter:
    draft_directory: drafts/twitter
    draft_mode: true
    hashtags:
      - RetailAI
      - CPG
      - EarningsAlert

# Claude prompt templates
prompts:
  analysis: |
    Analyze earnings call transcript or press release from {company}. Extract:
    1. Financial metrics (revenue, profit, etc.)
    2. Strategic initiatives
    3. Market trends
    4. Consumer behavior insights
    5. AI/Crypto/Tech observations
    6. Supply chain updates
    7. Forward-looking guidance
    Input: {content}
    Return JSON with keys: metrics, strategy, trends, consumer_insights, tech_observations, operations, outlook
  article: |
    Write a news article on {title_theme} from:
    {analyses_json}
    Requirements:
    - Professional tone, 800-1200 words
    - Include data points, quotes
    - Structure: headline, summary, body (subheadings)
    - Focus: investor/industry implications
    Return JSON: headline, summary, body, key_insights (array)
  twitter: |
    Create Twitter thread (3-5 tweets) from:
    Headline: {headline}
    Summary: {summary}
    Key Insights: {key_insights}
    Requirements:
    - First tweet: Hook + key stat, witty tone
    - Follow-up: Insights, engaging and clever
    - Final: Conclusion with call-to-action
    - Hashtags: {hashtags}
    - <280 chars/tweet
    Return JSON array of tweets
