version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://retailxai:password@postgres:5432/retailxai
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://retailxai:password@postgres:5432/retailxai
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    command: celery -A app.celery_app worker -Q publish,analyze -l INFO

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=retailxai
      - POSTGRES_USER=retailxai
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
