# Company configurations for data sources
companies:
  - name: Walmart
    youtube_channels:
      - UCX0-FP8iPvFwIHLG2NNfNVg
    rss_feed: https://corporate.walmart.com/newsroom/rss
    keywords:
      - retail
      - grocery
      - earnings
  - name: PepsiCo
    youtube_channels:
      - UCk3f5LKLrHRr5lzh4mW_mqw
    rss_feed: https://www.pepsico.com/news/rss
    keywords:
      - CPG
      - beverage
      - earnings
  - name: Tesla
    youtube_channels:
      - UCuAj0G44lNT7wRzLdeF7l1A  # Tesla Official
    rss_feed: https://www.tesla.com/rss
    keywords:
      - electric vehicles
      - automotive
      - energy
      - earnings
